# Generated by Django 6.1 on 2026-08-23 19:09

import panels.encoders
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identifier used to embed the panel, e.g. open-issues-by-tenant.', max_length=100, unique=True, verbose_name='slug')),
                ('title', models.CharField(help_text="Heading shown on the panel's card.", max_length=200, verbose_name='title')),
                ('sql', models.TextField(help_text='Runs read-only against the analytics schemas (silver, gold, bronze_*). Use %(name)s placeholders for parameters; never format values into the text.', verbose_name='SQL query')),
                ('options', models.JSONField(blank=True, default=dict, encoder=panels.encoders.PrettyJSONEncoder, help_text='The ECharts option object, as pasted from echarts.apache.org/examples. The query result is injected as dataset 0, so refer to its columns by name: series: [{type: "line", encode: {x: "day", y: "total"}}]. Group and filter with dataset.transform. A transform naming no source reads the query result; one that spells out fromDatasetIndex counts your own datasets from 1.', verbose_name='ECharts options')),
                ('parameters', models.JSONField(blank=True, default=dict, encoder=panels.encoders.PrettyJSONEncoder, help_text='Default values for the %(name)s placeholders, e.g. {"tenant": "project_a"}.', verbose_name='parameters')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('on_dashboard', models.BooleanField(default=False, help_text='Place this panel on the admin dashboard.', verbose_name='show on dashboard')),
                ('height', models.PositiveIntegerField(default=320, help_text='Height of the chart in pixels.', verbose_name='height')),
            ],
            options={
                'verbose_name': 'panel',
                'verbose_name_plural': 'panels',
                'ordering': ('title',),
            },
        ),
    ]
