"""
Django settings for crudman project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import secrets
from pathlib import Path

from django.urls import Resolver404, resolve

APP_NAME = os.environ.get("APP_NAME", "gefieder").capitalize()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY_FILE = Path("/run/secrets/django_secret_key")

SECRET_KEY = (
    SECRET_KEY_FILE.read_text().strip()
    if SECRET_KEY_FILE.exists()
    else secrets.token_hex(100)
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "false").strip().lower() == "true"

# The public host name of the server, set via the .env file in the repository root.
SERVER_NAME = os.environ.get("SERVER_NAME", "localhost")

# The base path under which the administration panel is served, set via the .env file
# in the repository root. It must match CRUDMAN_PATH of the proxy service and the URL
# configuration in crudman/urls.py.
CRUDMAN_PATH = os.environ.get("CRUDMAN_PATH", "crudman")

ALLOWED_HOSTS = ["localhost", "127.0.0.1", SERVER_NAME]

CSRF_TRUSTED_ORIGINS = [f"http://{SERVER_NAME}", f"https://{SERVER_NAME}"]

# Django matches the request's Origin against CSRF_TRUSTED_ORIGINS including scheme and
# port, so a dev setup reached on a non-default port (e.g. http://127.0.0.1:8080) needs
# that exact origin listed. CSRF_TRUSTED_ORIGINS holds a comma-separated list of extra
# origins; the local dev runner sets it to the address it publishes. It is only consulted
# in DEBUG mode so production keeps trusting SERVER_NAME alone.
if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        origin.strip()
        for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
        if origin.strip()
    ]

# In production the TLS-terminating reverse proxy is the only way in, so cookies are
# restricted to HTTPS and the forwarded protocol header is trusted. In development
# (DEBUG=true) the proxy serves plain HTTP instead.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    "unfold.contrib.constance",  # optional, if django-constance package is used
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.postgres',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'example.apps.ExampleConfig',
    'tenants.apps.TenantsConfig',
    'dropzones.apps.DropzonesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crudman.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crudman.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

PG_PASSWORD_FILE = Path("/run/secrets/crudman_password")

PG_PASSWORD = (
    PG_PASSWORD_FILE.read_text().strip()
    if PG_PASSWORD_FILE.exists()
    else secrets.token_hex(100)
)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'postgres'),
        'USER': os.environ.get('POSTGRES_USER', 'crudman'),
        'PASSWORD': PG_PASSWORD,
        'HOST': os.environ.get('POSTGRES_HOST', 'postgresql'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        'OPTIONS': {
            'options': '-c search_path=crudman,public',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = f'/{CRUDMAN_PATH}/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Where the dropzones app stores uploaded files. In the deployment this is the uploads
# volume, which the sqlmesh container mounts read-only at the same path so analytics
# models can open the files under the very paths the database rows point at. Without
# UPLOADS_DIR (local development, unit tests) a directory next to the app is used.
MEDIA_ROOT = Path(os.environ.get('UPLOADS_DIR', BASE_DIR / 'media'))

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


def _site_url(request):
    """Target for Unfold's "Return to site" link, or None to hide it.

    We currently serve no site root, so the default "/" would lead to a broken page.
    Returning None hides the link; it re-enables itself once a root route exists,
    because "/" then resolves. Unfold evaluates this per request.
    """
    try:
        resolve("/")
        return "/"
    except Resolver404:
        return None


UNFOLD = {
    # Browser tab title
    "SITE_TITLE": f"{APP_NAME} Administration",

    # Header text in the admin
    "SITE_HEADER": APP_NAME,

    # The "Return to site" link, hidden until there is a site root to return to.
    "SITE_URL": _site_url,
}