# Generated by Django 6.0.6 on 2026-06-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('name', models.CharField(help_text='e.g. max_mustermann or customer_a_project', max_length=50, primary_key=True, serialize=False, verbose_name='name')),
                ('connection_limit', models.IntegerField(blank=True, help_text='Maximum number of simultaneous database connections.', null=True, verbose_name='connection limit')),
                ('statement_timeout', models.CharField(blank=True, help_text='Maximum runtime of a single statement, e.g. 5min, 10s, 1h.', max_length=32, null=True, verbose_name='statement timeout')),
                ('work_mem', models.CharField(blank=True, help_text='Maximum memory per query operation, e.g. 256MB, 1GB.', max_length=32, null=True, verbose_name='work memory')),
                ('temp_file_limit', models.CharField(blank=True, help_text='Maximum size of a temporary file, e.g. 1GB.', max_length=32, null=True, verbose_name='temp file limit')),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
            },
        ),
    ]
