# Generated by Django 6.0.6 on 2026-06-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='connection_limit',
            field=models.IntegerField(blank=True, default=-1, help_text='Maximum number of simultaneous database connections. -1 means no limit.', null=True, verbose_name='connection limit'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='statement_timeout',
            field=models.CharField(blank=True, default='0', help_text='Maximum runtime of a single statement, e.g. 5min, 10s, 1h. 0 means no limit.', max_length=32, null=True, verbose_name='statement timeout'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='temp_file_limit',
            field=models.CharField(blank=True, default='0', help_text='Maximum size of a temporary file, e.g. 1GB. 0 means no limit.', max_length=32, null=True, verbose_name='temp file limit'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='work_mem',
            field=models.CharField(blank=True, default='0', help_text='Maximum memory per query operation, e.g. 256MB, 1GB. 0 means no limit.', max_length=32, null=True, verbose_name='work memory'),
        ),
    ]
