# Generated by Django 6.0.6 on 2026-06-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_connection_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='display_name',
            field=models.CharField(blank=True, help_text='e.g. Project A', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(help_text='Identifier used for the database role and bronze schema, e.g. project_a.', max_length=50, primary_key=True, serialize=False, verbose_name='slug'),
        ),
    ]
