CREATE SCHEMA IF NOT EXISTS crudman AUTHORIZATION crudman;

GRANT ALL PRIVILEGES ON SCHEMA crudman TO crudman;
ALTER DEFAULT PRIVILEGES IN SCHEMA crudman GRANT ALL ON TABLES TO crudman;
ALTER DEFAULT PRIVILEGES IN SCHEMA crudman GRANT ALL ON SEQUENCES TO crudman;
