# Generated by Django 6.1 on 2026-08-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identifier used to embed the panel, e.g. open-issues-by-tenant.', max_length=100, unique=True, verbose_name='slug')),
                ('title', models.CharField(help_text="Heading shown on the panel's card.", max_length=200, verbose_name='title')),
                ('sql', models.TextField(help_text='Runs read-only against the analytics schemas (silver, gold, bronze_*). Use %(name)s placeholders for parameters; never format values into the text.', verbose_name='SQL query')),
                ('chart_type', models.CharField(choices=[('bar', 'Bar'), ('line', 'Line'), ('pie', 'Pie'), ('scatter', 'Scatter'), ('table', 'Table')], default='bar', max_length=20, verbose_name='chart type')),
                ('x_field', models.CharField(blank=True, help_text='Result column for the category axis. Blank: the first column.', max_length=100, verbose_name='category column')),
                ('y_fields', models.CharField(blank=True, help_text='Comma-separated result columns to plot. Blank: all remaining columns.', max_length=500, verbose_name='value columns')),
                ('options', models.JSONField(blank=True, default=dict, help_text='Merged over the generated ECharts option object. Leave as {} for none.', verbose_name='ECharts options')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Default values for the %(name)s placeholders, e.g. {"tenant": "project_a"}.', verbose_name='parameters')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('on_dashboard', models.BooleanField(default=False, help_text='Place this panel on the admin dashboard.', verbose_name='show on dashboard')),
                ('height', models.PositiveIntegerField(default=320, help_text='Height of the chart in pixels.', verbose_name='height')),
            ],
            options={
                'verbose_name': 'panel',
                'verbose_name_plural': 'panels',
                'ordering': ('title',),
            },
        ),
    ]
