# Generated by Django 6.0.6 on 2026-09-05 20:07

import os

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grant_to_engine(apps, schema_editor):
    """Let the engine close the deployment row crudman opened for it.

    The engine runs in another container with no Django and no crudman, so it writes this
    one table directly. SELECT and UPDATE only, and on this table alone: it reports the
    outcome of a deployment, it does not decide one.

    The role name comes from the environment for the same reason every other one does --
    SQLMESH_DB_USER in buildtime.env may name a role a shared cluster already has.
    """
    role = os.environ.get("SQLMESH_DB_USER", "sqlmesh")
    schema_editor.execute(
        f"GRANT SELECT, UPDATE ON system_deployment TO {schema_editor.quote_name(role)}"
    )


def revoke_from_engine(apps, schema_editor):
    role = os.environ.get("SQLMESH_DB_USER", "sqlmesh")
    schema_editor.execute(
        f"REVOKE SELECT, UPDATE ON system_deployment FROM {schema_editor.quote_name(role)}"
    )


def adopt_the_tenants_app(apps, schema_editor):
    """Take over from the "tenants" app this one was renamed from.

    A no-op on a fresh installation, and on an upgrade it settles three things the rename
    would otherwise leave behind.

    The content types are re-pointed rather than recreated, which is the whole reason this
    runs. A permission belongs to a content type, and a group holds permissions, so
    renaming the label in place keeps every rank's rights exactly as an operator left them;
    deleting them and letting post_migrate make new ones would silently take an editor's
    tenant administration away.

    The old table is dropped rather than renamed because it never held anything of its own:
    PostgreSQL is the source of truth for a tenant and ``sync_tenants`` rebuilds the cache
    from the catalog on the next changelist view.
    """
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="tenants").update(app_label="system")

    schema_editor.execute("DROP TABLE IF EXISTS tenants_tenant")
    # Rows for an app that no longer exists. Harmless, but they make "showmigrations" lie.
    schema_editor.execute("DELETE FROM django_migrations WHERE app = 'tenants'")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # adopt_the_tenants_app re-points the content types the previous app label left.
        ("contenttypes", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('name', models.CharField(help_text='Identifier used for the database role and bronze schema, e.g. project_a.', max_length=50, primary_key=True, serialize=False, verbose_name='slug')),
                ('display_name', models.CharField(blank=True, help_text='e.g. Project A', max_length=100, verbose_name='name')),
                ('connection_limit', models.IntegerField(blank=True, default=-1, help_text='Maximum number of simultaneous database connections. -1 means no limit.', null=True, verbose_name='connection limit')),
                ('statement_timeout', models.CharField(blank=True, default='0', help_text='Maximum runtime of a single statement, e.g. 5min, 10s, 1h. 0 means no limit.', max_length=32, null=True, verbose_name='statement timeout')),
                ('work_mem', models.CharField(blank=True, default='0', help_text='Maximum memory per query operation, e.g. 256MB, 1GB. 0 means no limit.', max_length=32, null=True, verbose_name='work memory')),
                ('temp_file_limit', models.CharField(blank=True, default='0', help_text='Maximum size of a temporary file, e.g. 1GB. 0 means no limit.', max_length=32, null=True, verbose_name='temp file limit')),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(editable=False, max_length=40, verbose_name='commit')),
                ('main_sha', models.CharField(editable=False, max_length=40)),
                ('pinned', models.BooleanField(default=False, editable=False, help_text='A person chose this commit; the poll did not.')),
                ('status', models.CharField(choices=[('pending', 'Applying'), ('succeeded', 'Live'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('docs', models.JSONField(blank=True, default=dict, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('applied_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('requested_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'model version',
                'verbose_name_plural': 'model versions',
                'ordering': ('-created_on',),
                'get_latest_by': 'created_on',
            },
        ),
        migrations.RunPython(grant_to_engine, revoke_from_engine),
        migrations.RunPython(adopt_the_tenants_app, migrations.RunPython.noop),
    ]
