# Generated by Django 6.0.6 on 2026-09-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('checking_out', 'Checking out'), ('transforming', 'Transforming'), ('documenting', 'Generating docs'), ('succeeded', 'Live'), ('failed', 'Failed')], default='checking_out', max_length=16),
        ),
    ]
