# Generated by Django 6.0.6 on 2026-07-05 08:58

import django.db.models.deletion
import dropzones.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dropzone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Identifies the dropzone, also in analytics queries. e.g. bank-exports.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Purpose and agreed format of the files, shown on the upload page.')),
                ('upload_method', models.CharField(choices=[('browser', 'Browser upload'), ('api', 'API endpoint'), ('sftp', 'SFTP')], default='browser', help_text='How the files arrive. Only the browser upload is implemented yet.', max_length=10)),
                ('file_format', models.CharField(blank=True, help_text='Expected file type(s) as a comma-separated list like ".csv,.xlsx"; used to preselect matching files in the browser\'s file dialog.', max_length=100)),
                ('checker', models.CharField(blank=True, help_text='Function that inspects the uploaded files and rejects bad ones.', max_length=100)),
                ('converter', models.CharField(blank=True, help_text='Function that transforms the uploaded files into the stored files.', max_length=100)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unguessable part of the upload URL.', unique=True)),
                ('require_login', models.BooleanField(default=True, help_text='Off: anyone who knows the secret link may upload, without logging in.')),
                ('enabled', models.BooleanField(default=True, help_text='Off: the upload page answers 404, as if the link did not exist.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Users who may upload when a login is required. Empty means every logged-in user; superusers always may.', related_name='dropzones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dropzone',
                'verbose_name_plural': 'dropzones',
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField(blank=True, help_text='Start of the validity period; empty means valid from the beginning.', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='End of the validity period; empty means valid until replaced.', null=True)),
                ('directory', models.CharField(help_text='Directory of the stored files, relative to the uploads volume.', max_length=255)),
                ('sha256', models.CharField(help_text='One combined hash over all files as they were uploaded.', max_length=64)),
                ('dropzone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='dropzones.dropzone')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Empty for uploads through a secret link without login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'upload',
                'verbose_name_plural': 'uploads',
                'ordering': ['-uploaded_at'],
                'get_latest_by': 'uploaded_at',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=dropzones.models.upload_file_path)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dropzones.upload')),
            ],
            options={
                'verbose_name': 'uploaded file',
                'verbose_name_plural': 'uploaded files',
            },
        ),
    ]
