# Generated by Django 6.0.6 on 2026-07-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropzones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropzone',
            name='api_token',
            field=models.CharField(blank=True, help_text="Secret for the API endpoint, sent as an 'Authorization: Bearer <token>' header. An unattended API client cannot log in through the browser, so when this dropzone requires a login the token stands in for one; leave it empty to keep the endpoint open (only sensible without a login requirement).", max_length=64),
        ),
        migrations.AlterField(
            model_name='dropzone',
            name='upload_method',
            field=models.CharField(choices=[('browser', 'Browser upload'), ('api', 'API endpoint'), ('sftp', 'SFTP')], default='browser', help_text='How the files arrive. The browser and API uploads are implemented.', max_length=10),
        ),
    ]
