# Generated by Django 6.0.6 on 2026-08-19 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(editable=False, help_text='The PostgreSQL login role, derived from the username.', max_length=63, unique=True, verbose_name='database role')),
                ('group_role', models.CharField(editable=False, help_text="The gf_* group role carrying this user's privileges.", max_length=32, verbose_name='rank')),
                ('is_enabled', models.BooleanField(default=True, editable=False, help_text='Disabled roles keep everything they own but cannot connect.', verbose_name='enabled')),
                ('provisioned_on', models.DateTimeField(auto_now=True, verbose_name='provisioned')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='database_user', to=settings.AUTH_USER_MODEL, verbose_name='administrator')),
            ],
            options={
                'verbose_name': 'database user',
                'verbose_name_plural': 'database users',
                'ordering': ('role_name',),
            },
        ),
    ]
