# Generated by Django 6.0.6 on 2026-08-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseuser',
            name='awaiting_credential',
            field=models.BooleanField(default=True, editable=False, help_text="The password is issued on the user's next sign-in, once, to them.", verbose_name='awaiting credential'),
        ),
    ]
